loam_interface:
  ros__parameters:
    stateEstimationTopic: "aft_mapped_to_init"
    registeredScanTopic: "cloud_registered"
    flipStateEstimation: False
    flipRegisteredScan: False
    sendTF: False
    reverseTF: False

sensor_scan_generation:
  ros__parameters:
    lidar_frame: "right_mid360"
    vehicle_base_frame: "chassis"
    vel_ref_frame: "gimbal_yaw"

terrain_analysis:
  ros__parameters:
    scanVoxelSize: 0.05
    decayTime: 2.0
    noDecayDis: 4.0
    clearingDis: 8.0
    useSorting: True
    quantileZ: 0.4
    considerDrop: False
    limitGroundLift: False
    maxGroundLift: 0.15
    clearDyObs: True
    minDyObsDis: 0.3
    minDyObsAngle: 0.0
    minDyObsRelZ: -0.5
    absDyObsRelZThre: 0.2
    minDyObsVFOV: -16.0
    maxDyObsVFOV: 16.0
    minDyObsPointNum: 1
    noDataObstacle: False
    noDataBlockSkipNum: 0
    minBlockPointNum: 10
    vehicleHeight: 0.4
    voxelPointUpdateThre: 100
    voxelTimeUpdateThre: 2.0
    minRelZ: -2.5
    maxRelZ: 1.0
    disRatioZ: 0.2

terrain_analysis_ext:
  ros__parameters:
    scanVoxelSize: 0.1
    decayTime: 10.0
    noDecayDis: 0.0
    clearingDis: 30.0
    useSorting: False
    quantileZ: 0.1
    vehicleHeight: 0.4
    voxelPointUpdateThre: 100
    voxelTimeUpdateThre: 2.0
    lowerBoundZ: -2.5
    upperBoundZ: 1.0
    disRatioZ: 0.1
    checkTerrainConn: False                   # Check terrain connectivity
    terrainConnThre: 0.5
    terrainUnderVehicle: -0.75
    ceilingFilteringThre: 2.0
    localTerrainMapRadius: 4.0

local_planner:
  ros__parameters:
    pathFolder: $(find-pkg-share local_planner)/paths
    vehicleLength: 0.6
    vehicleWidth: 0.45
    sensorOffsetX: 0.0
    sensorOffsetY: 0.0
    twoWayDrive: True
    laserVoxelSize: 0.05
    terrainVoxelSize: 0.2
    useTerrainAnalysis: True
    checkObstacle: True
    checkRotObstacle: False
    adjacentRange: 4.25
    obstacleHeightThre: 0.15
    groundHeightThre: 0.1
    costHeightThre: 0.1
    costScore: 0.02
    useCost: False
    pointPerPathThre: 2
    minRelZ: -0.5
    maxRelZ: 0.25
    maxSpeed: 2.0
    dirWeight: 0.02
    dirThre: 90.0
    dirToVehicle: False
    pathScale: 1.25
    minPathScale: 0.75
    pathScaleStep: 0.25
    pathScaleBySpeed: True
    minPathRange: 1.0
    pathRangeStep: 0.5
    pathRangeBySpeed: True
    pathCropByGoal: True
    autonomyMode: True
    autonomySpeed: 2.0
    joyToSpeedDelay: 2.0
    joyToCheckObstacleDelay: 5.0
    goalClearRange: 0.5
    goalX: 0.0
    goalY: 0.0
    lookaheadDis: 1.0

path_follower:
  ros__parameters:
    sensorOffsetX: 0.0
    sensorOffsetY: 0.0
    pubSkipNum: 1
    twoWayDrive: True
    lookAheadDis: 0.5
    yawRateGain: 7.5
    stopYawRateGain: 7.5
    maxYawRate: 90.0
    maxSpeed: 2.0
    maxAccel: 2.5
    switchTimeThre: 1.0
    stopDisThre: 0.2
    slowDwnDisThre: 0.85
    useInclRateToSlow: False
    inclRateThre: 120.0
    slowRate1: 0.25
    slowRate2: 0.5
    slowTime1: 2.0
    slowTime2: 2.0
    useInclToStop: False
    inclThre: 45.0
    stopTime: 5.0
    autonomyMode: True
    autonomySpeed: 2.0
    joyToSpeedDelay: 2.0
